api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "test-transform"
type = "function"
uid = "e7b06956-e0a3-18cd-1377-cba4c07750bc1ec220fd"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
